version: "3.9"

services:
  node_backend:
    build: .
    container_name: auth_backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER_NAME=my_user
      - REDIS_PASSWORD=my_password
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:8.0-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=my_user
      - REDIS_PASSWORD=my_password
    command: >
      redis-server
      --requirepass mypassword
      --user myuser
    volumes:
      - redis-data:/data

volumes:
  redis-data: